ALTER TABLE users ADD COLUMN IF NOT EXISTS is_guest BOOLEAN DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS device_id_hash VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS ip_hash VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS is_migrated BOOLEAN DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS wallet_version BIGINT DEFAULT 1;